id: IB96A5845
legacy_id: P005454
ocr_import_info:
  bdrc_scan_id: W1AC58
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T22:24:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:39:03.973290+00:00'
last_modified: 2022-08-31 02:39:38.491826
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC58
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC58
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མདོ་མཁྱེན་བརྩེ་ཡེ་ཤེས་རྡོ་རྗེའི་རང་རྣམ་མཁའ་འགྲོའི་ཞལ་ལུང་།
  author: མདོ་མཁྱེན་བརྩེ་ཡེ་ཤེས་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.6426779293901274
  ocr_word_median_confidence_index: 0.6800000071525574
quality: null
bases:
  I4PD958:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD958
      total_pages: 430
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD958.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6426779293901274
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
