id: P005454
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC58
  title: མདོ་མཁྱེན་བརྩེ་ཡེ་ཤེས་རྡོ་རྗེའི་རང་རྣམ་མཁའ་འགྲོའི་ཞལ་ལུང་།
  author: ''
  volumes:
    a70be36569994b38a44c3c1dd31eac28:
      image_group_id: I4PD958
      title: ''
      volume_number: 1
      total_pages: 430
      base_file: v001.txt
